### ISSUE TITLE
Is help

### ISSUE THREAD

**Issue by Nedjii** [BentoBoxWorld/BSkyBlock#189]
Hello, i suggest to add a permission for /is help so we can deny its usage and make our own help command or i suggest an opion to fully disable the is help command from bentobox,
regards.

**Comment by tastybento** [comment]
it's too embedded in the system. you can adjust the text in the locale files.

**Comment by Nedjii** [comment]
If we want to hide some messages it's not possible, is help should be a real part of the config instead of taking every command sentences.

**Comment by tastybento** [comment]
Yeah, sorry. Right now commands can only have one permission. Help for any command already has that set to be the same permission as the command. It's not possible to add another permission.

**Comment by Nedjii** [comment]
I didn't mean putting a permission per command help but a real part of the config being the /is help, meaning you could actually put whatever you want in it instead of making it automatically.

**Comment by tastybento** [comment]
You can do this now. Let me explain. Here is part of the us-EN.yml file:

```
commands:
  # Parameters in <> are required, parameters in [] are optional
  help:
    header: "&7=========== &c[label] help &7==========="
    syntax: "&b[usage] &a[parameters]&7: &e[description]"
    syntax-no-parameters: "&b[usage]&7: &e[description]"
    end: "&7================================="
    parameters: "[command]"
    description: "help command"
    console: "Console"
  admin:
    help:
      description: "admin command"
    resets:
      description: "edit resets of the players"
```
In the syntax section, you can completely customize what you want to show. If you do not want the usage and parameters shown, then just remove those placeholders. But keep the [description] one because then for each command, you can write the description how you like.

Does this get you what you want?
