### ISSUE TITLE
Wandering Trader damage

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/BSkyBlock#215]
#### Describe the bug

Visitors can damage/kill a wandering trader

#### Steps to reproduce the behavior

1. Spawn a Wandering Trader or wait for one to appear
2. Let a visitor hit him

#### Expected behavior

Wandering Traders should be protected imho

#### Server

 - OS: **Linux**
 - Java version: **Openjdk 1.8.0_212**

#### Plugins

```
BentoBox, ChestShop, dynmap*, LuckPerms, mcMMO, PlaceholderAPI*, PlugMan, Vault, WorldBorder, WorldEdit, WorldGuard
```

##### BentoBox and Addons

```
Running Paper 1.14.4.
BentoBox version: 1.8.0-SNAPSHOT-b1422
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, End
Loaded Addons:
Biomes 1.6.0.2-SNAPSHOT-b142 (ENABLED)
BSkyBlock 1.8.0-SNAPSHOT-b500 (ENABLED)
Challenges 0.9.0-SNAPSHOT-#385 (ENABLED)
Level 1.7.0-SNAPSHOT-b284 (ENABLED)
Limits 1.7.0 (ENABLED)
MagicCobblestoneGenerator 1.7.0.2 (ENABLED)
Warps 1.8.0-SNAPSHOT-b187 (ENABLED)
```

##### Configuration

 - Database: **JSON** 

### Additional context

```
  flags:
    HURT_MONSTERS: false
    HURT_VILLAGERS: false

  default-island-flags:
    HURT_MONSTERS: 0
    HURT_VILLAGERS: 500
```
