### ISSUE TITLE
MFH Grind Hoppers don't work in Bskyblock_world

### ISSUE THREAD

**Issue by ianmcvann** [BentoBoxWorld/BSkyBlock#337]
#### Describe the bug

I've recently installed the MFHopper plugin, which implements mob grind hoppers as one of its core features. The hoppers work in every world except the bskyblock_world, where they don't deal damage. I've contacted the plugin's developer, and he says the damage to mobs is suffocation damage. I suspect that bskyblock is somehow blocking this.

#### Steps to reproduce the behavior

Install MFHoppers, enable auto kill,  and attempt to use grind hopper in bskyblock world. 
#### Expected behavior

Mobs should take damage.
##### BentoBox Version (Mandatory)

```
1.13.1
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
I can't replicate this issue right now.

I used this config for MFHoppers:

```
  "grindHopper":
    type: Grind
    limitPerChunk: -1 #-1 no limit
    name: "&8[&aMobGrind&8] &7Hopper"
    lore:
      - "&7This hopper teleports specified monster type"
      - "&7To it's location & freezes them"
      - "&a&l* &7Current mob: %type%"
    should_drop_from_explosions: true #This options makes that hopper drops from explosions.
    mob: CREEPER
    allowNamedMobs: false
    onlyActiveWhenOwnerIsOnline: false
    damageType: CUSTOM #Can be any minecraft damage type
    mob-blacklist:
      - "ENDER_DRAGON"
    #If you want auto kill put, isAuto: true
    isAuto: true
    #If you want so the hoppers works for every mob, isGlobal: true
    damage: 5
    stack_kill: 0
    time: 1
    inventoryTitle: "&bGrind Hopper &a(1)"
    DropToInventory: true

    #This will move every 4 seconds 10 amount of item out of hopper to if linked chest!
    linkedInstantMove: true
    linkedMoveEvery: 4
    linkedMoveAmount: 10
    linkedLimit: 1

    sellEvery: 10
    sellAmount: 10
```

Reloaded the config:

`/mfhoppers reload`

Gave myself a hopper:

`mfhoppers give tastybento grindHopper 3`

Placed the hopper on my island.

Went into creative mode and spawned a creeper near the hopper. It was teleported to the hopper and died pretty quickly.

<img width="848" alt="Screen Shot 2020-05-31 at 5 12 51 PM" src="https://user-images.githubusercontent.com/4407265/83366145-10ab3680-a362-11ea-98bf-6b972b886ea1.png">

If this doesn't work for you, then share your BSkyBlock config.yml.

Also, do `/bbox version` and share that and let me know what other plugins you are using `/plugins`.
