### ISSUE TITLE
Spawning BSkyblock build 677 and up

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/BSkyBlock#394]
#### Describe the bug

From build 677 and higher, the spawning is poor
Normal: 20 mobs per player
Now: around 5 per player

#### Steps to reproduce the behavior

Default test server
Start with Bskyblock build 675
Count mobs by butchering them a few times
![2021-01-05_22 15 02](https://user-images.githubusercontent.com/28690790/103699670-93087280-4fa3-11eb-8db4-5e539786d3e8.png)

Now start with Bskyblock build 677
Count mobs by butchering them a few times
![2021-01-05_22 08 38](https://user-images.githubusercontent.com/28690790/103699702-9e5b9e00-4fa3-11eb-8633-6e4ad03380f8.png)

##### Output of `/bbox version` (Mandatory)

```
[22:16:30 INFO]: Running Invalid (PURPUR) 1.16.4.
[22:16:30 INFO]: BentoBox version: 1.16.0-SNAPSHOT-b1947
[22:16:30 INFO]: Database: JSON
[22:16:30 INFO]: Loaded Game Worlds:
[22:16:30 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, The End
[22:16:30 INFO]: Loaded Addons:
[22:16:30 INFO]: Biomes 1.14.0-SNAPSHOT-b198 (ENABLED)
[22:16:30 INFO]: BSkyBlock 1.14.2-SNAPSHOT-b675 (ENABLED)
[22:16:30 INFO]: Challenges 0.8.4-SNAPSHOT-b438 (ENABLED)
[22:16:30 INFO]: Level 2.5.1 (ENABLED)
[22:16:30 INFO]: Limits 1.15.2 (ENABLED)
[22:16:30 INFO]: MagicCobblestoneGenerator 2.3.0-SNAPSHOT-b202 (ENABLED)
[22:16:30 INFO]: Warps 1.10.2 (ENABLED)
```

#### Plugins (Optional)

```
_______
```

**Comment by tastybento** [comment]
You can adjust the mob spawn rate in the config.yml. The earlier versions were setting it to -1 which according to the API _should_ be the server setting, but due to a server bug was actually causing the spawning to occur every tick! So, that was fixed. If you want more mobs then set it to 1 but watch out for lag.

**Comment by x1p** [comment]
With default `-1` it should take the paper values.
I've set it to 30 as an example. That gave me 2 mobs.

**Comment by tastybento** [comment]
> With default `-1` it should take the paper values.

It does now, but before Build 677 there is a bug in the Bukkit API that means that `-1` is actually == `1`. So, if you want Build 677 and higher to generate at the same rate as before, set the following in config.yml:

```
spawn-limits:
    # Spawn limits. These override the limits set in bukkit.yml
    # If set to a negative number, the server defaults will be used
    # Added since 1.11.2.
    monsters: 1
    # Added since 1.11.2.
    animals: 1
    # Added since 1.11.2.
    water-animals: 1
    # Added since 1.11.2.
    ambient: 1
    # Setting to 0 will disable animal spawns, but this is not recommended. Minecraft default is 400.
    # A negative value uses the server default
    # Added since 1.11.2.
    ticks-per-animal-spawns: 1
    # Setting to 0 will disable monster spawns, but this is not recommended. Minecraft default is 400.
    # A negative value uses the server default
    # Added since 1.11.2.
    ticks-per-monster-spawns: 1
```
