### ISSUE TITLE
Superflat chunk clearer is not working

### ISSUE THREAD

**Issue by condblock** [BentoBoxWorld/BSkyBlock#505]
### Expected behavior

fixed superflat chunk 

### Observed/Actual behavior

![image](https://github.com/BentoBoxWorld/BSkyBlock/assets/72214833/7a92bf06-bb74-40d2-9dc8-f7facf97a689)

### Steps/models to reproduce

![image](https://github.com/BentoBoxWorld/BSkyBlock/assets/72214833/12b9fc6a-741e-414a-86a0-714ce2a1b098)
![image](https://github.com/BentoBoxWorld/BSkyBlock/assets/72214833/8c6951a6-0692-4b12-8008-9459a10ff323)
![image](https://github.com/BentoBoxWorld/BSkyBlock/assets/72214833/dce64227-3ab7-4214-8dc8-e4d5bd849b12)
my setting files

### BentoBox version

[12:57:21 INFO]: 작동중 PURPUR 1.20.1.
[12:57:21 INFO]: BentoBox 버전: 1.24.1
[12:57:21 INFO]: 데이터베이스: JSON
[12:57:21 INFO]: 불러온 게임 월드:
[12:57:21 INFO]: bskyblock_world (BSkyBlock): 오버월드, 지옥, 엔더월드
[12:57:21 INFO]: 불러온 애드온:
[12:57:21 INFO]: Biomes 2.1.1 (ENABLED)
[12:57:21 INFO]: Border 4.1.1 (ENABLED)
[12:57:21 INFO]: BSkyBlock 1.16.1 (ENABLED)
[12:57:21 INFO]: Chat 1.1.4 (ENABLED)
[12:57:21 INFO]: ControlPanel 1.13.0 (ENABLED)
[12:57:21 INFO]: DragonFights 1.7.0 (ENABLED)
[12:57:21 INFO]: ExtraMobs 1.12 (ENABLED)
[12:57:21 INFO]: Likes 2.3.1 (ENABLED)
[12:57:21 INFO]: Limits 1.19.1 (ENABLED)
[12:57:21 INFO]: MagicCobblestoneGenerator 2.5.1 (ENABLED)
[12:57:21 INFO]: Visit 1.6.0 (ENABLED)

### Plugin list

[12:58:35] [Server thread/INFO]: Bukkit Plugins: (97):
[12:58:35] [Server thread/INFO]: - AcceptTheRules, AdvancedMobArena, antiRedstoneClock, AutoPickup, BaritoneRemover, BentoBox, BentoBox-Biomes, BentoBox-BSkyBlock, BentoBox-Likes, BentoBox-Limits
[12:58:35] [Server thread/INFO]: BentoBox-MagicCobblestoneGenerator, BentoBox-Visit, BetterEconomy, BetterProfiles, BossBarHealth, BustaMine, Citizens, ClientDetector, ColoredEnderChests, ConsoleSpamFix
[12:58:35] [Server thread/INFO]: CoreProtect, DecentHolograms, DeluxeMenus, DiscordSRV, DragonFights, DyedBackpacks, DynamicShop, DynaTech, ElectricSpawners, *Ersatz
[12:58:35] [Server thread/INFO]: ExcellentCrates, ExtraGear, ExtraTools, FastAsyncWorldEdit, ForcePack, Galactifun, HardcoreSlimefun, Images, InfinityExpansion, InteractiveChat
[12:58:35] [Server thread/INFO]: InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LibsDisguises, Liquid, LuckPerms, MCCosmetics, MinecraftDashboard
[12:58:35] [Server thread/INFO]: ModelEngine, Multiverse-Core, Multiverse-Portals, MythicMobs, NBTAPI, NexEngine, NoCollisions, PlaceholderAPI, PlayerAuctions, PlayerPoints
[12:58:35] [Server thread/INFO]: PrivateStorage, ProtocolLib, Quests, *ServerTutorialPlus, SetSpawn, SFCalc, SfChunkInfo, *SharpSK, SimpleUtils, SkBee
[12:58:35] [Server thread/INFO]: SkJade, *skLib, SkQuery, Skript, *skUtilities, SlimeCustomizer, Slimefun, SlimefunOreChunks, SlimeHUD, SlimeTinker
[12:58:35] [Server thread/INFO]: SoulJars, SoundMuffler, spark, SuperVanish, TAB, TabCompleteFilter, Themis, TradeSystem, TranscEndence, Vault
[12:58:35] [Server thread/INFO]: VentureChat, VillagerNerf, Votifier, VotingPlugin, WhatIsThis, WildLoaders, WorldGuard

Other

**Comment by BONNe** [comment]
Could you remove multiverse core and check if then it works?

**Comment by condblock** [comment]
```
    bskyblock_world:
    ==: MVWorld
    hidden: 'false'
    alias: bskyblock_world
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 9.0
      y: -64.0
      z: 8.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '6615286955424450035'
    generator: BentoBox
    playerLimit: '-1'
    allowFlight: 'true'
  bskyblock_world_nether:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '8.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 86.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NETHER
    seed: '-7999410695942740827'
    generator: BentoBox
    playerLimit: '-1'
    allowFlight: 'true'
  bskyblock_world_the_end:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '16.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: NORMAL
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 0.0
      y: 85.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: THE_END
    seed: '-2631314625255549279'
    generator: BentoBox
    playerLimit: '-1'
    allowFlight: 'true'
    ```
    the generator is assigned to Bentobox
