### ISSUE TITLE
Asynchronous commands?

### ISSUE THREAD

**Issue by FlailoftheLord** [BentoBoxWorld/BSkyBlock#90]
So, i'm working on creating a custom Gui using BSP, and came across a bug or issues...
The plugin's telling me that the skyblock comands its running when i click, are Asynchronous??

```

28.02 13:08:18 [Server] WARN [BossShopPro] Plugin BossShopPro v2.0.2 generated an exception while executing task 1456
28.02 13:08:18 [Server] INFO java.lang.IllegalStateException: Asynchronous command dispatch!
28.02 13:08:18 [Server] INFO at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[Spigot.jar:git-Spigot-4165cd8-cb98c6e]
28.02 13:08:18 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[Spigot.jar:git-Spigot-4165cd8-cb98c6e]
28.02 13:08:18 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.performCommand(CraftPlayer.java:323) ~[Spigot.jar:git-Spigot-4165cd8-cb98c6e]
28.02 13:08:18 [Server] INFO at org.black_ixx.bossshop.core.rewards.BSRewardTypePlayerCommand.giveReward(BSRewardTypePlayerCommand.java:50) ~[?:?]
28.02 13:08:18 [Server] INFO at org.black_ixx.bossshop.core.BSBuy.purchase(BSBuy.java:522) ~[?:?]
28.02 13:08:18 [Server] INFO at org.black_ixx.bossshop.misc.ShopItemPurchaseTask.run(ShopItemPurchaseTask.java:45) ~[?:?]
28.02 13:08:18 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[Spigot.jar:git-Spigot-4165cd8-cb98c6e]
28.02 13:08:18 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot.jar:git-Spigot-4165cd8-cb98c6e]
28.02 13:08:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
28.02 13:08:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
28.02 13:08:18 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

```

There's the exact error. I'm trying to make it run /island create custom-island
Is this an issue with Skyblock?

If not, then i'll just go to their place for support, i'm just not sure if this is a problem specifically with BSkyblock, as i've never seen this when using commands from other plugins.

**Comment by tastybento** [comment]
From this stack trace I can't see where it's hitting BentoBox or BSkyBlock. It looks like the player is performing a command async and that's what's being caught. I'd check the error on BossShopPro and see what they say.

**Comment by FlailoftheLord** [comment]
> From this stack trace I can't see where it's hitting BentoBox or BSkyBlock. It looks like the player is performing a command async and that's what's being caught. I'd check the error on BossShopPro and see what they say.

Okay, as an additional update, i created an alias command through MyCommand, BSP now accepts the command, but MyCommand now won't run it.
![2019-03-01_09h06_59](https://user-images.githubusercontent.com/41513161/53643213-807fbe00-3c01-11e9-9e66-b55c2b53f19e.png)

**Comment by tastybento** [comment]
I can't replicate this error right now. I tried with [MyCommand V5.3.4](https://dev.bukkit.org/projects/mycommand/files) and created these commands:

```
bsb_help:
  command: /bh
  type: ALIAS
  alias: /skyblock help
basic_island:
  command: /basicisland
  type: ALIAS
  alias: /skyblock create spruce
```

I also changed the BSkyBlock command:
```
# BSkyBlock Configuration 1.3.0-SNAPSHOT
bskyblock:
  command:
    # Island Command. What command users will run to access their island.
    # To define alias, just separate commands with white space.
    island: skyblock
    # The island admin command.
    # To define alias, just separate commands with white space.
    admin: bsbadmin bsb
```

I made a "spruce island" and deleted my alt and had it issue the /basicisland command:

```
>bsb delete LSPvicky
[07:50:51 INFO]: Type command again within 10s to confirm.
>bsb delete LSPvicky
[07:50:53 INFO]: Island at -128,120,0 has been successfully deleted.
[07:50:53 INFO]: Success!
[07:50:57 INFO]: LSPvicky issued server command: /basicisland
[07:50:57 INFO]: LSPvicky issued mycmd command ID(2) /basicisland
[07:50:57 INFO]: LSPvicky issued server command: /skyblock create spruce
[07:50:57 ERROR]: [BentoBox] Tried to paste schem 'nether-spruce' for BSkyBlock_world_nether but the schem is not loaded!
[07:50:57 INFO]: [BentoBox] This might be due to an invalid schem format. Keep in mind that schems are not schematics.
[07:51:43 INFO]: LSPvicky issued server command: /skyblock
[07:51:48 INFO]: LSPvicky lost connection: Disconnected
[07:51:48 INFO]: LSPvicky left the game
```

The island created fine.

So, I don't see any issues so far. I'm not sure why you are seeing problems.
