### ISSUE TITLE
use-own-generator doesn't work

### ISSUE THREAD

**Issue by TheWranger** [BentoBoxWorld/BSkyBlock#94]
**Description**
Use-own generator does not prevent the addon from using its own generator

**Steps to reproduce the behavior:**
1. Set 'Use-own-generator' to true
2. Start server up; addon still uses its own generator

**Expected behavior**
The addon will not use its own generator and let the server generate the world

**Server Information:**

[Please complete the following information:]
 - YAML
 - Paperspigot
 - Linux
 - Java 8
 - BentoBox v1.3 Snapshot (Latest
```
22.02 02:19:40 [Server] INFO AcidIsland 1.3.0-SNAPSHOT
22.02 02:19:40 [Server] INFO Challenges 0.5.0-SNAPSHOT
22.02 02:19:40 [Server] INFO Biomes 0.5.0-SNAPSHOT
22.02 02:19:40 [Server] INFO Level 1.2.1-SNAPSHOT
22.02 02:19:40 [Server] INFO Limits 0.1.0-SNAPSHOT
```
**Additional Context**
Only tested with AcidIsland. Tested with latest snapshot of AcidIsland and Bentobox.
Even if you tell another generator to generate the world (through bukkit.yml) while `use-own-generator` is enabled; BentoBox/the addon will still overwrite the generator.

**Comment by tastybento** [comment]
WIP haha
<img width="851" alt="Screen Shot 2019-03-09 at 10 18 24 AM" src="https://user-images.githubusercontent.com/4407265/54075487-cc131700-4254-11e9-8536-fa66590e582e.png">

**Comment by tastybento** [comment]
To make it work, you'll need to set use-own-generator to **true** and also add the worlds to the bukkit.yml file, e.g.:

```
worlds:
  cleanroom:
    generator: CleanroomGenerator:1|minecraft:grass_block[snowy=true]
  cleanroom_nether:
    generator: CleanroomGenerator:1|minecraft:grass_block[snowy=true]
  cleanroom_the_end:
    generator: CleanroomGenerator:1|minecraft:grass_block[snowy=true]
```
